import { Prisma } from "@prisma/client";
import type { SectionRepository } from "../types";
import type { SectionInstance, SectionContent, CreatedBy } from "@/app/editor/pageState";
import type { SectionProminence, SectionRhythm } from "@/app/types/landing";
import type { StrategyDNA } from "@/app/ai/types/dna";

interface SectionRow {
  id: string;
  pageId: string;
  order: number;
  type: string;
  variant: string;
  content: unknown;
  prominence: string;
  rhythm: string;
  themeOverrides: unknown;
  visibility: string;
  locked: boolean;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
  version: number;
}

// Bug found live (via an end-to-end test against a real database, not caught by any
// unit test - the in-memory SectionRepository stores sections in a Map keyed by pageId,
// so it has no way to reproduce a cross-page collision): `SectionInstance.id` is
// generated by app/editor/pageState.ts's fromLandingPage as `${type}-${index}` (e.g.
// "hero-0") - unique within one page's own sections array, which is the only invariant
// the domain layer ever needed. But prisma/schema.prisma's `Section.id` is a GLOBAL
// primary key, so a second project's "hero-0" collided with the first's, throwing a
// unique-constraint violation on the very first multi-project write. Same root cause,
// same fix shape as createProjectFromGeneration's page-id bug (app/lib/projectService.ts):
// scope the value that has to be globally unique in Postgres by prefixing it with
// something that already is (pageId, itself now a real cuid), while every other layer -
// the domain SectionInstance type, Operation.sectionId inside the JSON-persisted
// operation log, the renderer - keeps using the original short id, exactly as generated.
// dbId/domainId are the only two places that ever need to know this prefix exists.
function dbId(pageId: string, sectionId: string): string {
  return `${pageId}::${sectionId}`;
}

function domainId(row: Pick<SectionRow, "id" | "pageId">): string {
  const prefix = `${row.pageId}::`;
  return row.id.startsWith(prefix) ? row.id.slice(prefix.length) : row.id;
}

function toInstance(row: SectionRow): SectionInstance {
  return {
    id: domainId(row),
    type: row.type as SectionInstance["type"],
    variant: row.variant,
    content: row.content as SectionContent,
    layout: { prominence: row.prominence as SectionProminence, rhythm: row.rhythm as SectionRhythm },
    themeOverrides: row.themeOverrides as Partial<StrategyDNA>,
    visibility: row.visibility as "visible" | "hidden",
    locked: row.locked,
    metadata: {
      createdBy: row.createdBy as CreatedBy,
      createdAt: row.createdAt.getTime(),
      updatedAt: row.updatedAt.getTime(),
      // `label` is optional and not persisted as its own column yet (no caller sets it
      // today) - re-added here, not dropped, the moment a real use appears.
    },
    version: row.version,
  };
}

export class PrismaSectionRepository implements SectionRepository {
  constructor(private readonly prisma: Prisma.TransactionClient) {}

  // No inner $transaction: every caller already runs inside one (see
  // RepositoryBundle.transaction), and an interactive transaction client cannot open a
  // nested one. Atomicity comes from the caller's transaction; createMany replaces the
  // previous N individual create() calls, so a 10-section page costs 2 statements per
  // edit instead of 11.
  async replaceAll(pageId: string, sections: readonly SectionInstance[]): Promise<void> {
    await this.prisma.section.deleteMany({ where: { pageId } });

    if (sections.length === 0) return;

    await this.prisma.section.createMany({
      data: sections.map((section, order) => ({
        id: dbId(pageId, section.id),
        pageId,
        order,
        type: section.type,
        variant: section.variant,
        content: (section.content ?? Prisma.JsonNull) as unknown as Prisma.InputJsonValue,
        prominence: section.layout.prominence,
        rhythm: section.layout.rhythm,
        themeOverrides: section.themeOverrides as object,
        visibility: section.visibility,
        locked: section.locked,
        createdBy: section.metadata.createdBy,
        createdAt: new Date(section.metadata.createdAt),
        updatedAt: new Date(section.metadata.updatedAt),
        version: section.version,
      })),
    });
  }

  async list(pageId: string): Promise<SectionInstance[]> {
    const rows = await this.prisma.section.findMany({ where: { pageId }, orderBy: { order: "asc" } });
    return rows.map(toInstance);
  }
}
