import type { LandingPage, SectionRhythm } from "@/app/types/landing";
import type { ThemeConfig } from "@/app/styles/theme";
import type { LayoutPersonality } from "@/app/styles/layout";
import { resolveSectionSpacing } from "@/app/styles/layout";
import GlowBackground from "./ui/GlowBackground";
import SectionHeader from "./ui/SectionHeader";

type FeaturesProps = {
  items: LandingPage["features"];
  theme: ThemeConfig;
  layout: LayoutPersonality;
  rhythm: SectionRhythm;
  variant?: string;
};

type ListProps = { items: LandingPage["features"]; theme: ThemeConfig; layout: LayoutPersonality };

function FeaturesGrid({ items, theme, layout }: ListProps) {
  return (
    <div className={`mt-20 grid gap-8 ${layout.gridColumns}`}>
      {items.map((feature, index) => (
        <div
          key={index}
          className={`group relative overflow-hidden ${layout.cardRadius} border ${layout.cardPadding} backdrop-blur transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl`}
          style={{ borderColor: theme.colors.border, background: theme.colors.card, color: theme.colors.primary }}
        >
          <div
            className="absolute -right-10 -top-10 h-32 w-32 rounded-full blur-3xl opacity-0 transition duration-500 group-hover:opacity-100"
            style={{ background: theme.gradients.glow }}
          />

          <div className="relative">
            <div
              className="flex h-14 w-14 items-center justify-center rounded-2xl text-2xl text-white shadow-lg"
              style={{ backgroundImage: theme.gradients.button }}
            >
              {feature.icon}
            </div>

            <h3 className="mt-8 text-2xl font-bold">{feature.title}</h3>

            <p className="mt-4 leading-7" style={{ color: theme.colors.secondary }}>{feature.description}</p>

            <div className="mt-8 flex items-center gap-2 text-sm font-medium" style={{ color: theme.colors.accent }}>
              Learn more
              <span className="transition-transform duration-300 group-hover:translate-x-1">→</span>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

function FeaturesList({ items, theme }: ListProps) {
  return (
    <div className="mt-20 divide-y border-t" style={{ borderColor: theme.colors.border }}>
      {items.map((feature, index) => (
        <div key={index} className="flex items-start gap-6 py-8">
          <div
            className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl text-xl text-white"
            style={{ backgroundImage: theme.gradients.button }}
          >
            {feature.icon}
          </div>

          <div>
            <h3 className="text-xl font-bold">{feature.title}</h3>
            <p className="mt-2 leading-7" style={{ color: theme.colors.secondary }}>{feature.description}</p>
          </div>
        </div>
      ))}
    </div>
  );
}

export default function Features({ items, theme, layout, rhythm, variant }: FeaturesProps) {
  return (
    <section className={`relative ${resolveSectionSpacing(layout.sectionSpacing, rhythm)} overflow-hidden`}>
      <GlowBackground theme={theme} decorative={layout.decorative}>
        <div className={`mx-auto ${layout.sectionWidth}`}>
          <SectionHeader
            theme={theme}
            layout={layout}
            eyebrow="Everything you need"
            title={
              <>
                Powerful features,
                <br />
                built for conversions
              </>
            }
            description="Every landing page generated by Noctra is designed to maximize trust, engagement and conversion."
          />

          {variant === "list" ? (
            <FeaturesList items={items} theme={theme} layout={layout} />
          ) : (
            <FeaturesGrid items={items} theme={theme} layout={layout} />
          )}
        </div>
      </GlowBackground>
    </section>
  );
}
