// @vitest-environment happy-dom
import { describe, it, expect, afterEach } from "vitest";
import { render, cleanup } from "@testing-library/react";
import Landing from "./Landing";
import { fromLandingPage } from "@/app/editor/pageState";
import { buildPipeline } from "@/app/ai/builders/PipelineBuilder";
import { BENCHMARK_BUSINESSES } from "@/app/benchmark/businesses";
import type { LandingPage } from "@/app/types/landing";

// Section headings were hardcoded in the components, so every generated page - for every
// industry - carried the same second- and third-largest headlines. A family law firm and a
// dental clinic shared them word for word. 703 tests passed throughout: nothing about a
// component rendering a constant string is wrong in isolation, and no test compared two
// businesses' output to each other. These do.
function pageFor(prompt: string) {
  const pipeline = buildPipeline(prompt);
  const landing = {
    dna: pipeline.dna,
    sections: [...pipeline.sections],
    site: {
      seo: { title: "", description: "", keywords: [], ogTitle: "", ogDescription: "" },
      branding: { primaryColor: "", secondaryColor: "", accentColor: "", fontHeading: "", fontBody: "", logoPrompt: "" },
      images: { heroPrompt: "", ogImagePrompt: "" },
    },
    hero: {
      badge: "Badge",
      title: "A Distinctive Headline",
      highlightWord: "Distinctive",
      subtitle: "Subtitle.",
      primaryCTA: "Go",
      secondaryCTA: "More",
      imageStyle: "website",
      imagePrompt: "",
      stats: [],
    },
    stats: [],
    features: [{ title: "F", description: "d", icon: "*" }],
    benefits: [{ title: "B", description: "d", icon: "*" }],
    testimonials: [{ name: "N", company: "C", text: "t" }],
    pricing: [],
    faq: [{ question: "q", answer: "a" }],
    footer: { company: "Co", email: "e@x.pt", copyright: "(c)" },
  } as unknown as LandingPage;

  const { container } = render(<Landing state={fromLandingPage(landing)} />);
  return container.textContent ?? "";
}

describe("generated pages never carry our own marketing copy", () => {
  afterEach(cleanup);

  // This one string was rendered on every page: a paying customer's published website
  // told their visitors that it was "generated by Noctra".
  const FORBIDDEN = [
    "generated by Noctra",
    "Noctra",
    "Powerful features, built for conversions",
    "Benefits that make",
    "Everything you need",
    "Why choose us",
    "maximize trust, engagement and conversion",
  ];

  it("renders none of it, for any business in the corpus", () => {
    for (const business of BENCHMARK_BUSINESSES.slice(0, 6)) {
      const text = pageFor(business.prompt);
      for (const phrase of FORBIDDEN) {
        expect(text, `${business.id} rendered "${phrase}"`).not.toContain(phrase);
      }
      cleanup();
    }
  });
});

describe("two different businesses do not render the same headings", () => {
  afterEach(cleanup);

  it("shares no invented marketing headline between a law firm and a dental clinic", () => {
    // The exact pair that exposed this when their outputs were placed side by side.
    const law = pageFor("A small law firm helping local families with wills and estate planning.");
    cleanup();
    const dental = pageFor("A family dental clinic offering check-ups and cosmetic dentistry.");

    // Plain section nouns are shared on purpose - a heading that just says "Features" is
    // invisible. What must never be shared is authored copy, which is what a long phrase
    // indicates.
    const longPhrases = (text: string) =>
      text
        .split(/(?<=[.!?])\s+/)
        .map((s) => s.trim())
        .filter((s) => s.split(/\s+/).length >= 5);

    const shared = longPhrases(law).filter((phrase) => dental.includes(phrase));
    expect(shared).toEqual([]);
  });
});
