import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Landing from "@/app/components/Landing";
import { repos } from "@/app/lib/repos";
import { loadPublishedSite } from "@/app/lib/publishService";

// THE PUBLIC SITE
//
// The first surface in this product that is not for the person who built it. No auth,
// no session, no editor chrome - a stranger opens a URL and sees a business's page.
//
// Read-only by construction, not by convention: Landing takes an optional
// onDispatchOperation, and this route simply never passes one, so every EditableText
// downstream renders as plain text with no click handler and no hover affordance. The
// same component tree serves the editor and the published site, and there is no way for
// an editing capability to leak here by accident.
//
// Serving costs one row read: the published snapshot is materialized at publish time
// (see app/lib/publishService.ts), never replayed from the operation log.

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const site = await loadPublishedSite(repos, slug);

  if (!site) {
    return { title: "Not found" };
  }

  // site.seo has been generated by the pipeline and persisted since the beginning, and
  // until now was never rendered anywhere - the product asked the model for a title,
  // description and keywords on every generation and then dropped them. This is where
  // that data finally reaches HTML.
  const { seo } = site.state.site;
  const title = seo.title?.trim() || site.projectName;
  const description = seo.description?.trim() || undefined;

  return {
    title,
    description,
    keywords: seo.keywords?.length ? seo.keywords : undefined,
    openGraph: {
      title: seo.ogTitle?.trim() || title,
      description: seo.ogDescription?.trim() || description,
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: seo.ogTitle?.trim() || title,
      description: seo.ogDescription?.trim() || description,
    },
    robots: { index: true, follow: true },
  };
}

export default async function PublishedSitePage({ params }: Props) {
  const { slug } = await params;
  const site = await loadPublishedSite(repos, slug);

  // One 404 for "no such slug", "not published" and "published then taken down" alike -
  // a visitor must not be able to tell an unpublished project apart from one that never
  // existed.
  if (!site) {
    notFound();
  }

  return (
    <main className="min-h-screen">
      <Landing state={site.state} />
    </main>
  );
}
