import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Landing from "@/app/components/Landing";
import { repos } from "@/app/lib/repos";
import { loadPublishedSite } from "@/app/lib/publishService";
import { appUrl } from "@/app/lib/appUrl";
import RestaurantSchema from "./RestaurantSchema";
import SiteEvents from "./SiteEvents";

// THE PUBLIC SITE
//
// The first surface in this product that is not for the person who built it. No auth,
// no session, no editor chrome - a stranger opens a URL and sees a business's page.
//
// Read-only by construction, not by convention: Landing takes an optional
// onDispatchOperation, and this route simply never passes one, so every EditableText
// downstream renders as plain text with no click handler and no hover affordance. The
// same component tree serves the editor and the published site, and there is no way for
// an editing capability to leak here by accident.
//
// Serving costs one row read: the published snapshot is materialized at publish time
// (see app/lib/publishService.ts), never replayed from the operation log.

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const site = await loadPublishedSite(repos, slug);

  if (!site) {
    return { title: "Not found" };
  }

  // site.seo has been generated by the pipeline and persisted since the beginning, and
  // until now was never rendered anywhere - the product asked the model for a title,
  // description and keywords on every generation and then dropped them. This is where
  // that data finally reaches HTML.
  const { seo } = site.state.site;
  const title = seo.title?.trim() || site.projectName;
  const description = seo.description?.trim() || undefined;

  // A FOTOGRAFIA QUE APARECE QUANDO ALGUÉM PARTILHA O RESTAURANTE
  //
  // Um restaurante é partilhado por WhatsApp mais vezes do que é encontrado no Google, e até
  // aqui o cartão saía só com texto. A fotografia do hero é a que o dono escolheu para ser a
  // primeira coisa que se vê - não há razão para gerar outra por cima dela.
  //
  // Sem fotografia nenhuma (um hero editorial, ou o PEXELS_API_KEY em falta) fica sem
  // `images` em vez de com uma imagem falsa. Um cartão sem foto é pior do que um com foto;
  // um cartão com a foto errada é pior do que os dois.
  const hero = site.state.sections.find((section) => section.type === "hero")?.content as
    | { image?: { url: string; width: number; height: number; alt: string } | null }
    | undefined;

  const photo = hero?.image?.url ? hero.image : null;
  const images = photo
    ? [{ url: photo.url, width: photo.width, height: photo.height, alt: photo.alt }]
    : undefined;

  const path = `/${slug}`;

  return {
    title,
    description,
    keywords: seo.keywords?.length ? seo.keywords : undefined,
    // O endereço verdadeiro deste site, sem o ?fbclid=... que o Facebook cola a cada
    // partilha e sem o ?utm_source=... do QR code na ementa. Cada um desses criava, para o
    // Google, mais uma cópia do mesmo restaurante a competir com o original.
    alternates: { canonical: path },
    openGraph: {
      title: seo.ogTitle?.trim() || title,
      description: seo.ogDescription?.trim() || description,
      type: "website",
      // Resolvido contra o metadataBase (app/layout.tsx). Sem `url`, quem partilha um
      // endereço com parâmetros de campanha vê o cartão apontar para esse endereço.
      url: path,
      siteName: site.projectName,
      locale: "pt_PT",
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: seo.ogTitle?.trim() || title,
      description: seo.ogDescription?.trim() || description,
      images,
    },
    robots: { index: true, follow: true },
  };
}

export default async function PublishedSitePage({ params }: Props) {
  const { slug } = await params;
  const site = await loadPublishedSite(repos, slug);

  // One 404 for "no such slug", "not published" and "published then taken down" alike -
  // a visitor must not be able to tell an unpublished project apart from one that never
  // existed.
  if (!site) {
    notFound();
  }

  return (
    <main className="min-h-screen">
      {/* What turns a blue link into a card with the address, the hours and a call button
          on the phone of someone standing on the street. For a local business that card is
          the search result that matters. */}
      {/* Absoluto, não `/${slug}`: o schema.org exige URLs completas e descarta em silêncio
          as que não sejam - o cartão do restaurante deixava de aparecer sem erro nenhum. */}
      <RestaurantSchema state={site.state} siteUrl={`${appUrl()}/${slug}`} />
      {/* Counts taps on the actions, and nothing about the person tapping. */}
      <SiteEvents projectId={site.projectId} />
      <Landing state={site.state} />
    </main>
  );
}
