import { cache } from "react";
import type { Metadata } from "next";
import type { HeroData } from "@/app/types/landing";
import { notFound } from "next/navigation";
import Landing from "@/app/components/Landing";
import { cachedPublishedSite } from "@/app/lib/siteCache";
import { appUrl } from "@/app/lib/appUrl";
import RestaurantSchema from "./RestaurantSchema";
import SiteEvents from "./SiteEvents";

// THE PUBLIC SITE
//
// The first surface in this product that is not for the person who built it. No auth,
// no session, no editor chrome - a stranger opens a URL and sees a business's page.
//
// Read-only by construction, not by convention: Landing takes an optional
// onDispatchOperation, and this route simply never passes one, so every EditableText
// downstream renders as plain text with no click handler and no hover affordance. The
// same component tree serves the editor and the published site, and there is no way for
// an editing capability to leak here by accident.
//
// Serving costs one row read: the published snapshot is materialized at publish time
// (see app/lib/publishService.ts), never replayed from the operation log.

// MEDIDO, NÃO DEDUZIDO: 4,8 → 2,6 VARRIMENTOS POR VISITA
//
// O `generateMetadata` e o componente precisam do mesmo site, e cada um pedia o seu.
//
// Eu tinha escrito que isso eram "duas idas ao Postgres". Estava errado, e a medição
// apanhou-me. Contado com `pg_stat_user_tables`, cinco visitas de cada vez:
//
//                     chamadas    Project    Page     total por visita
//   sem memoização      2/visita    1/visita  3,8       4,8
//   com memoização      1/visita    1/visita  1,6       2,6
//
// A tabela `Project` NUNCA fez duas consultas: o `findUnique` do Prisma tem um dataloader
// que junta chamadas idênticas no mesmo tick numa só. O desperdício real estava no `Page` —
// o `listPages` é um `findMany`, que o dataloader não junta, e esse corria mesmo duas vezes.
//
// Portanto o ganho é real e é 46%, mas não pela razão que eu tinha escrito.
//
// O `cache` do React desduplica dentro do MESMO pedido - a segunda chamada devolve o que a
// primeira trouxe, sem tocar na base de dados. Não é uma cache entre visitas: dois
// visitantes continuam a ser duas consultas, e uma edição publicada aparece à visita
// seguinte, que é o comportamento que já existia.
//
// Vive aqui e não dentro do `loadPublishedSite` de propósito: o serviço fica puro e
// testável sem um contexto de React à volta, e a memoização fica onde o pedido existe.
// As duas camadas fazem coisas diferentes e ambas fazem falta: o `cache` do React desduplica
// dentro do MESMO pedido (o generateMetadata e o componente pedem o mesmo site), e a cache do
// Next guarda entre pedidos, invalidada por etiqueta ao publicar. Ver app/lib/siteCache.ts.
const siteFor = cache((slug: string) => cachedPublishedSite(slug));

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const site = await siteFor(slug);

  if (!site) {
    return { title: "Not found" };
  }

  // site.seo has been generated by the pipeline and persisted since the beginning, and
  // until now was never rendered anywhere - the product asked the model for a title,
  // description and keywords on every generation and then dropped them. This is where
  // that data finally reaches HTML.
  const { seo } = site.state.site;
  const title = seo.title?.trim() || site.projectName;
  const description = seo.description?.trim() || undefined;

  // A FOTOGRAFIA QUE APARECE QUANDO ALGUÉM PARTILHA O RESTAURANTE
  //
  // Um restaurante é partilhado por WhatsApp mais vezes do que é encontrado no Google, e até
  // aqui o cartão saía só com texto. A fotografia do hero é a que o dono escolheu para ser a
  // primeira coisa que se vê - não há razão para gerar outra por cima dela.
  //
  // Sem fotografia nenhuma (um hero editorial, ou o PEXELS_API_KEY em falta) fica sem
  // `images` em vez de com uma imagem falsa. Um cartão sem foto é pior do que um com foto;
  // um cartão com a foto errada é pior do que os dois.
  const hero = site.state.sections.find((section) => section.type === "hero")?.content as
    | HeroData
    | undefined;

  const photo = hero?.image?.url ? hero.image : null;
  const images = photo
    ? [{ url: photo.url, width: photo.width, height: photo.height, alt: photo.alt }]
    : undefined;

  // `site.slug`, não o `slug` do pedido. São iguais - o site só foi encontrado porque bateu
  // certo - mas o que se declara ao Google como endereço oficial desta página tem de vir de
  // onde está guardado, e não de uma string que chegou de fora. É a mesma regra que fechou o
  // BLOCKER #3 no checkout.
  const path = `/${site.slug}`;

  return {
    title,
    description,
    keywords: seo.keywords?.length ? seo.keywords : undefined,
    // O endereço verdadeiro deste site, sem o ?fbclid=... que o Facebook cola a cada
    // partilha e sem o ?utm_source=... do QR code na ementa. Cada um desses criava, para o
    // Google, mais uma cópia do mesmo restaurante a competir com o original.
    alternates: { canonical: path },
    openGraph: {
      title: seo.ogTitle?.trim() || title,
      description: seo.ogDescription?.trim() || description,
      type: "website",
      // Resolvido contra o metadataBase (app/layout.tsx). Sem `url`, quem partilha um
      // endereço com parâmetros de campanha vê o cartão apontar para esse endereço.
      url: path,
      siteName: site.projectName,
      locale: "pt_PT",
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: seo.ogTitle?.trim() || title,
      description: seo.ogDescription?.trim() || description,
      images,
    },
    robots: { index: true, follow: true },
  };
}

export default async function PublishedSitePage({ params }: Props) {
  const { slug } = await params;
  const site = await siteFor(slug);

  // One 404 for "no such slug", "not published" and "published then taken down" alike -
  // a visitor must not be able to tell an unpublished project apart from one that never
  // existed.
  if (!site) {
    notFound();
  }

  return (
    <main className="min-h-screen">
      {/* What turns a blue link into a card with the address, the hours and a call button
          on the phone of someone standing on the street. For a local business that card is
          the search result that matters. */}
      {/* Absoluto, não `/${slug}`: o schema.org exige URLs completas e descarta em silêncio
          as que não sejam - o cartão do restaurante deixava de aparecer sem erro nenhum. */}
      <RestaurantSchema state={site.state} siteUrl={`${appUrl()}/${site.slug}`} />
      {/* Counts taps on the actions, and nothing about the person tapping. */}
      <SiteEvents projectId={site.projectId} />
      <Landing state={site.state} />
    </main>
  );
}
